#include "fmalloc_internal.h"

#include "fmalloc_runtime.inc"
#include "fmalloc_vector.inc"
#include "fmalloc_altrep.inc"
#include "fmalloc_backend.inc"
#include "fmalloc_ops.inc"
#include "fmalloc_ooc.inc"
#include "fmalloc_tensor.inc"
#include "fmalloc_alp.inc"
#include "fmalloc_sparse.inc"
#include "fmalloc_bed.inc"
#include "fmalloc_dosage.inc"
#include "fmalloc_hap.inc"
#include "fmalloc_insitu.inc"
#include "fmalloc_api.inc"
